[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 2  # Adjust verbosity level to suppress warnings

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[fmt]
line_length = 120

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
